model_list:
  - model_name: class-chat-model
    litellm_params:
      model: gemini/gemini-3.1-flash-lite
      api_key: os.environ/GEMINI_API_KEY

general_settings:
  master_key: sk-vibe-summer-2026
